# Use the official Bun image
FROM oven/bun:1 as base

# Set the working directory
WORKDIR /app

# Copy package.json and bun.lockb (if exists)
COPY package.json bun.lockb* ./

# Install dependencies
RUN bun install --frozen-lockfile

# Copy the rest of the application code
COPY . .

# Build the application
RUN bun run build

# Define environment variables
ENV NEYNAR_API_KEY
ENV NEYNAR_SIGNER_UUID
ENV NEYNAR_POLL_SIGNER_UUID
ENV SUPABASE_URL
ENV SUPABASE_KEY
ENV SENTRY_DSN
ENV SENTRY_ENVIRONMENT
ENV WEB3_ENGINE_URL
ENV WEB3_ACCESS_TOKEN
ENV TRANSACTION_ADDRESS
ENV ALCHEMY_API_KEY
ENV EDGE_FUNCTIONS_SERVER_URL
ENV EDGE_FUNCTIONS_SECRET_TOKEN
ENV FRAME_API_URL
ENV APP_URL
ENV WARPCAST_API_KEY
ENV NEXT_GENERAL_QUESTION_CRON
ENV NEXT_COMMUNITY_QUESTION_CRON
ENV NEXT_EXPEDITED_QUESTION_CRON
ENV NEXT_QUESTION_REPLY
ENV NEXT_QUESTION_INFO
ENV NEXT_POLL_RESULTS_CRON
ENV NEXT_POLL_RESULTS_INTERVAL_HOURS
ENV NEXT_PREDICTIVE_POLL_RESULTS_CRON
ENV NEXT_QUESTION_QUAL_UPDATE_CRON
ENV NEXT_QUESTION_QUAL_UPDATE_INTERVAL_HOURS
ENV CALL_TO_ACTION
ENV RESULTS_CALL_TO_ACTION
ENV LOG_LEVEL

# Start the application
CMD ["bun", "run", "start"]