# Use the official Bun image
FROM oven/bun:1 as base

# Set the working directory
WORKDIR /app

# Copy package.json and bun.lockb (if exists)
COPY package.json bun.lockb* ./

# Install dependencies
RUN bun install --frozen-lockfile

# Copy the rest of the application code
COPY . .

# Build the application
RUN bun run build

# Define environment variables
ARG NEYNAR_API_KEY
ARG NEYNAR_SIGNER_UUID
ARG NEYNAR_POLL_SIGNER_UUID
ARG SUPABASE_URL
ARG SUPABASE_KEY
ARG SENTRY_DSN
ARG SENTRY_ENVIRONMENT
ARG WEB3_ENGINE_URL
ARG WEB3_ACCESS_TOKEN
ARG TRANSACTION_ADDRESS
ARG ALCHEMY_API_KEY
ARG EDGE_FUNCTIONS_SERVER_URL
ARG EDGE_FUNCTIONS_SECRET_TOKEN
ARG FRAME_API_URL
ARG APP_URL
ARG WARPCAST_API_KEY
ARG NEXT_GENERAL_QUESTION_CRON
ARG NEXT_COMMUNITY_QUESTION_CRON
ARG NEXT_EXPEDITED_QUESTION_CRON
ARG NEXT_QUESTION_REPLY
ARG NEXT_QUESTION_INFO
ARG NEXT_POLL_RESULTS_CRON
ARG NEXT_POLL_RESULTS_INTERVAL_HOURS
ARG NEXT_PREDICTIVE_POLL_RESULTS_CRON
ARG NEXT_QUESTION_QUAL_UPDATE_CRON
ARG NEXT_QUESTION_QUAL_UPDATE_INTERVAL_HOURS
ARG CALL_TO_ACTION
ARG RESULTS_CALL_TO_ACTION
ARG LOG_LEVEL
ARG NODE_ENV

# Start the application
CMD ["bun", "run", "./dist/app.js"]
